
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8762/auth/oauth/token
      userAuthorizationUri: http://localhost:8762/auth/oauth/authorize
      clientId: sso1
      clientSecret: secret
#      scope: ROLE_API
      registered-redirect-uri: http://localhost:8780/sso/
#      pre-established-redirect-uri: http://localhost:8762/client/r/r1
      # 默认true，是否使用默认重定向url，
      use-current-uri: false
#      authorized-grant-types: authorization_code
#      id: sso1
    resource:
      user-info-uri: http://localhost:8762/auth/user


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud-oauth2?useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
    service:
      name: sso
server:
  port: 8780
  servlet:
    context-path: /sso

logging:
  level:
    org.springframework.security: info
    com.netflix.discovery: 'OFF'


